# Generated by Django 3.2 on 2021-05-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210504_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='lattitude',
        ),
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(default='NaN', max_length=10),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='point',
            name='z',
            field=models.CharField(default='NaN', max_length=50),
        ),
    ]
