# Generated by Django 3.2 on 2021-05-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20210505_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='flowers',
            field=models.BooleanField(default=0),
        ),
    ]
