# Generated by Django 3.2 on 2021-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_point_flowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='flowers',
        ),
        migrations.AddField(
            model_name='point',
            name='datum',
            field=models.CharField(choices=[('0', 'WGS84'), ('1', 'Пулково 42')], default='WGS84', max_length=10),
        ),
    ]
